// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOcuAjaTUsaY0YFEyw9yeBVn8qhbxrL90',
    appId: '1:687014930504:web:f6a32932e6c3cd399fd07d',
    messagingSenderId: '687014930504',
    projectId: 'ayna-kunal',
    authDomain: 'ayna-kunal.firebaseapp.com',
    storageBucket: 'ayna-kunal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATJL0sWqTLdLeFh__-oAhheV0lKCuiObQ',
    appId: '1:687014930504:android:7ef363d795a4cd4d9fd07d',
    messagingSenderId: '687014930504',
    projectId: 'ayna-kunal',
    storageBucket: 'ayna-kunal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA-_4Xzh58OosoPvWm7TVQK13yOLLetqI',
    appId: '1:687014930504:ios:c0a82e0c38042bf59fd07d',
    messagingSenderId: '687014930504',
    projectId: 'ayna-kunal',
    storageBucket: 'ayna-kunal.appspot.com',
    iosBundleId: 'com.example.aynaChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA-_4Xzh58OosoPvWm7TVQK13yOLLetqI',
    appId: '1:687014930504:ios:c0a82e0c38042bf59fd07d',
    messagingSenderId: '687014930504',
    projectId: 'ayna-kunal',
    storageBucket: 'ayna-kunal.appspot.com',
    iosBundleId: 'com.example.aynaChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOcuAjaTUsaY0YFEyw9yeBVn8qhbxrL90',
    appId: '1:687014930504:web:b6d3071ac072d39a9fd07d',
    messagingSenderId: '687014930504',
    projectId: 'ayna-kunal',
    authDomain: 'ayna-kunal.firebaseapp.com',
    storageBucket: 'ayna-kunal.appspot.com',
  );

}